name: Publish prereleases

on:
  push:
    branches: [main, experimental, ethan/experimental]
  pull_request:
    branches: [main, experimental]

jobs:
  release:
    name: Publish builder package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: pnpm -F cloudflare run build

      - name: Publish to NPM
        run: pnpm exec pkg-pr-new publish --pnpm './packages/cloudflare'
